/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goa;
import booking.BookingUI;
/**
 *
 * @author ravi g
 */
public class JW_marriottUI extends javax.swing.JFrame {

    String City = "Goa";
    public String check_in = "", check_out = "";
    public int rooms , adults , childs ;
    public void setDetails(int room, int adult,int child,String c_in, String c_out)
    {
        rooms = room;
        adults = adult;
        childs = child;
        check_in = c_in;
        check_out = c_out;
        //JOptionPane.showMessageDialog(null,rooms + " " + adults + " " + childs + " " + check_in + " " + check_out);
    }
    
    String first_name = "", last_name = "",email_ID = "", mobile_no = "";
    
    public void set_user_info(String f_name, String l_name, String email,String mobile)
    {
        first_name = f_name;
        last_name = l_name;
        email_ID = email;
        mobile_no = mobile;
    }
    public JW_marriottUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pic1 = new javax.swing.JButton();
        pic2 = new javax.swing.JButton();
        pic3 = new javax.swing.JButton();
        J_book3 = new javax.swing.JButton();
        J_book1 = new javax.swing.JButton();
        J_book2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("JW Marriott");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("P,O, Road, Near KFC, Near Calangute Circle, North Goa, Goa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Amenities");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 157, -1, -1));

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JWpic1 - Copy.jpg"))); // NOI18N
        pic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic1ActionPerformed(evt);
            }
        });
        getContentPane().add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 157, 192, 110));

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JWpic2 - Copy.jpg"))); // NOI18N
        pic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic2ActionPerformed(evt);
            }
        });
        getContentPane().add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 296, 192, 109));

        pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JW pic3 - Copy.jpg"))); // NOI18N
        pic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic3ActionPerformed(evt);
            }
        });
        getContentPane().add(pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 439, 192, 110));

        J_book3.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        J_book3.setText("Book Now");
        J_book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_book3ActionPerformed(evt);
            }
        });
        getContentPane().add(J_book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 520, -1, -1));

        J_book1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        J_book1.setText("Book Now");
        J_book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_book1ActionPerformed(evt);
            }
        });
        getContentPane().add(J_book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 244, -1, -1));

        J_book2.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        J_book2.setText("Book Now");
        J_book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_book2ActionPerformed(evt);
            }
        });
        getContentPane().add(J_book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 377, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anlogo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 201, 313, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("<html>Elegant, contemporary rooms come with terraces, flat-screen TVs, free Wi-Fi and minibars, plus tea and coffeemaking facilities. Upgraded rooms add whirlpool baths, sea views and access to a club lounge; some include dining areasAmenities include an Australian restaurant, an informal Indian restaurant, an all-day restaurant serving eastern cuisine, plus 2 bars and a pastry shop.<html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 292, 213, 279));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Rs. 30,446/-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 520, -1, 21));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jw marriott logo.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("<html>Minimum stay of 1 night, Free WIFI Connection upto 3 Devices, Lunch & Dinner are provided.<html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 181, 329, 45));

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("* To see full view of room click on picture.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 570, 216, 23));

        jLabel10.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Superior Room with Balcony  View ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 439, -1, -1));

        jLabel11.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Superior Rooms with Garden View");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 157, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Rs. 21,110/-");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 378, -1, 27));

        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("<html>Rates included accomodation,Buffer Breakfast At Capital Kitchen, Free Transport Facility, Mini Bar, Electronic Safe are provided, Early Departure Fee Applicable.<html>");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 469, 329, 45));

        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("<html>All meals are provided, free wifi connection upto 4 devices, one way transport facility, balcony, AC, 24 hour room service available.<html>");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 326, 329, 45));

        jLabel15.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Executive Room with Pool View");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 295, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Rs. 13,000/-");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 244, 104, 27));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JWblur.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic1ActionPerformed
        JW_pic1 open = new JW_pic1();
            open.setVisible(true);
    }//GEN-LAST:event_pic1ActionPerformed

    private void pic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic2ActionPerformed
        JW_pic2 open = new JW_pic2();       
            open.setVisible(true);
    }//GEN-LAST:event_pic2ActionPerformed

    private void pic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic3ActionPerformed
       JW_pic3 open = new JW_pic3();
            open.setVisible(true);
    }//GEN-LAST:event_pic3ActionPerformed

    private void J_book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_book1ActionPerformed
        BookingUI open = new BookingUI();
        open.setVisible(true);
        open.setDetails_B(City, "JW Marriott","P,O, Road, Near KFC, Near Calangute Circle, North Goa, Goa", "Superior Rooms with Garden View", rooms, adults, childs, check_in, check_out, 13000);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
    }//GEN-LAST:event_J_book1ActionPerformed

    private void J_book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_book2ActionPerformed
        BookingUI open = new BookingUI();
        open.setVisible(true);
        open.setDetails_B(City, "JW Marriott","P,O, Road, Near KFC, Near Calangute Circle, North Goa, Goa", "Executive Room with Pool View", rooms, adults, childs, check_in, check_out, 21110);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
    }//GEN-LAST:event_J_book2ActionPerformed

    private void J_book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_book3ActionPerformed
        BookingUI open = new BookingUI();
        open.setVisible(true);
        open.setDetails_B(City, "JW Marriott","P,O, Road, Near KFC, Near Calangute Circle, North Goa, Goa", "Superior Room with Balcony View", rooms, adults, childs, check_in, check_out, 30446);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
    }//GEN-LAST:event_J_book3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JW_marriottUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JW_marriottUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JW_marriottUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JW_marriottUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JW_marriottUI().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton J_book1;
    private javax.swing.JButton J_book2;
    private javax.swing.JButton J_book3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton pic1;
    private javax.swing.JButton pic2;
    private javax.swing.JButton pic3;
    // End of variables declaration//GEN-END:variables
}
