/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delhi;
import booking.BookingUI;
/**
 *
 * @author sanjeev
 */
public class Radisson_BluUI extends javax.swing.JFrame {

    String City = "Delhi";
    public String check_in = "", check_out = "";
    public int rooms , adults , childs ;
    public void setDetails(int room, int adult,int child,String c_in, String c_out)
    {
        rooms = room;
        adults = adult;
        childs = child;
        check_in = c_in;
        check_out = c_out;
        //JOptionPane.showMessageDialog(null,rooms + " " + adults + " " + childs + " " + check_in + " " + check_out);
    }
    String first_name = "", last_name = "",email_ID = "", mobile_no = "";
    
    public void set_user_info(String f_name, String l_name, String email,String mobile)
    {
        first_name = f_name;
        last_name = l_name;
        email_ID = email;
        mobile_no = mobile;
    }
    
    public Radisson_BluUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        R_pic1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        R_book1 = new javax.swing.JButton();
        R_pic2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        R_book2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        R_pic3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        R_book3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/Radisson Blu logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Radisson Blu Plaza");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 29, -1, -1));

        jLabel3.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("National Highway – 8  Mahipalpur, Near I.G.I. Airport (T3), New Delhi.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel4.setBackground(java.awt.Color.lightGray);
        jLabel4.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Superior Rooms");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 120, -1, -1));

        R_pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/rad small 1.png"))); // NOI18N
        R_pic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_pic1ActionPerformed(evt);
            }
        });
        getContentPane().add(R_pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 120, 224, 122));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html> Free WIFI Desk, Coffee Table, Shower, LCD TV, Hot & Cold Running Water, Attached Bathroom. <html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 151, 432, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rs. 9,812/-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 187, 120, -1));

        R_book1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        R_book1.setText("Book Now");
        R_book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_book1ActionPerformed(evt);
            }
        });
        getContentPane().add(R_book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 189, -1, -1));

        R_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/rad small 2.png"))); // NOI18N
        R_pic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_pic2ActionPerformed(evt);
            }
        });
        getContentPane().add(R_pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 272, 224, 129));

        jLabel8.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Premium Rooms");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 272, 432, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html> Free WiFi, complimentary breakfast, complimentary two way airport transfers, Living Area, Newspaper, Hot & Cold Running Water, Attached Bathroom. </html>");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 462, 432, 30));

        R_book2.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        R_book2.setText("Book Now");
        R_book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_book2ActionPerformed(evt);
            }
        });
        getContentPane().add(R_book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 343, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rs. 13,378/-");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 498, 140, -1));

        R_pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/rad small 3.png"))); // NOI18N
        R_pic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_pic3ActionPerformed(evt);
            }
        });
        getContentPane().add(R_pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 431, 224, 129));

        jLabel10.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Business Class Rooms");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 431, 432, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<html> Free WiFI, Sofa, Attached Bathroom, Mini-bar, Desk, Shower, Bathtub, Hot & Cold Running Water. </html>");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 305, 432, 30));

        R_book3.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        R_book3.setText("Book Now");
        R_book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_book3ActionPerformed(evt);
            }
        });
        getContentPane().add(R_book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1068, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rs. 10,704/-");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 341, 140, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Amenities");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 106, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/Amenities.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 155, 366, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("<html> Free WiFi Internet, <br> Swimming Pool, <br> Bakery, <br> Restaurant, <br> Bar, <br> Gymnasium/Health Club, <br> Spa, <br> Banquet facilities, <br> Business Center, <br> Meeting Rooms, <br> Wi-Fi Internet, <br> Room Service, <br> Front desk, <br> Hair/Beauty Salon, <br> Wedding services, <br> Free WiFi and more. <html>");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 282, 366, 370));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("* To see full view of room click on picture");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 230, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/Back radisson.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void R_pic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_pic1ActionPerformed
        Rad_pic1 open = new Rad_pic1();
        open.setVisible(true);
    }//GEN-LAST:event_R_pic1ActionPerformed

    private void R_pic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_pic2ActionPerformed
        Rad_pic2 open = new Rad_pic2();
        open.setVisible(true);
    }//GEN-LAST:event_R_pic2ActionPerformed

    private void R_pic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_pic3ActionPerformed
        Rad_pic3 open = new Rad_pic3();
        open.setVisible(true);
    }//GEN-LAST:event_R_pic3ActionPerformed

    private void R_book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_book1ActionPerformed
        BookingUI open = new BookingUI();
        open.setDetails_B(City, "Radisson Blu Plaza","National Highway – 8  Mahipalpur, Near I.G.I. Airport (T3), New Delhi.", "Superior Rooms", rooms, adults, childs, check_in, check_out, 9812);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_R_book1ActionPerformed

    private void R_book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_book2ActionPerformed
        BookingUI open = new BookingUI();
        open.setDetails_B(City, "Radisson Blu Plaza","National Highway – 8  Mahipalpur, Near I.G.I. Airport (T3), New Delhi.", "Premium Rooms", rooms, adults, childs, check_in, check_out, 10704);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_R_book2ActionPerformed

    private void R_book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_book3ActionPerformed
        BookingUI open = new BookingUI();
        open.setDetails_B(City, "Radisson Blu Plaza","National Highway – 8  Mahipalpur, Near I.G.I. Airport (T3), New Delhi.", "Business Class Rooms", rooms, adults, childs, check_in, check_out, 13378);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);        
    }//GEN-LAST:event_R_book3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Radisson_BluUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Radisson_BluUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Radisson_BluUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Radisson_BluUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Radisson_BluUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton R_book1;
    private javax.swing.JButton R_book2;
    private javax.swing.JButton R_book3;
    private javax.swing.JButton R_pic1;
    private javax.swing.JButton R_pic2;
    private javax.swing.JButton R_pic3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
