/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delhi;

import booking.BookingUI;

/**
 *
 * @author sanjeev
 */
public class Taj_PalaceUI extends javax.swing.JFrame {

    String City = "Delhi";
    public String check_in = "", check_out = "";
    public int rooms , adults , childs ;
    public void setDetails(int room, int adult,int child,String c_in, String c_out)
    {
        rooms = room;
        adults = adult;
        childs = child;
        check_in = c_in;
        check_out = c_out;
        //JOptionPane.showMessageDialog(null,rooms + " " + adults + " " + childs + " " + check_in + " " + check_out);
    }
    String first_name = "", last_name = "",email_ID = "", mobile_no = "";
    
    public void set_user_info(String f_name, String l_name, String email,String mobile)
    {
        first_name = f_name;
        last_name = l_name;
        email_ID = email;
        mobile_no = mobile;
    }
    
    public Taj_PalaceUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pic1 = new javax.swing.JButton();
        pic2 = new javax.swing.JButton();
        pic3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        T_book1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        T_book2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        T_book3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/taj_logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(216, 216, 216));
        jLabel2.setText("Taj Palace");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 33, -1, -1));

        jLabel3.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(216, 216, 216));
        jLabel3.setText("2 Sardar Patel Marg Diplomatic Enclave, New Delhi.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 88, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("<html> Reception, Free Wi-Fi, <br>  Internet, Indoor Swimming Pool, <br> Swimming Pool, Valet Parking, <br> Café, Restaurant, <br> Bar, Gymnasium/Health, <br> ClubAirport Shuttle (Complimentary), <br> Body treatments, Massage, <br> Sauna, Spa, Steam bath, <br> Business services, Conference Facilities, <br> Babysitting/Child Services, Children's play area, <br> Board Room, Business Center, <br> Wi-Fi Internet, Room Service, <br> Car Rental, Travel Desk, <br> Tennis Court, Translation services, <br> Live Entertainment and more. <html>");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 303, 366, 349));

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/taj small 1.png"))); // NOI18N
        pic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic1ActionPerformed(evt);
            }
        });
        getContentPane().add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 119, 222, 124));

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/Taj small 2.png"))); // NOI18N
        pic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic2ActionPerformed(evt);
            }
        });
        getContentPane().add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 273, 222, 125));

        pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/tak small 3.png"))); // NOI18N
        pic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic3ActionPerformed(evt);
            }
        });
        getContentPane().add(pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 428, 222, 125));

        jLabel4.setBackground(java.awt.Color.lightGray);
        jLabel4.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Superior Room Twin Bed City Or Pool View");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html>Minimum Stay of 2 Nights. Rate Includes Basic WiFi up to 4 Devices.<br> Early Departure Fee Applicable.</html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 150, 432, 30));

        T_book1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        T_book1.setText("Book Now");
        T_book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_book1ActionPerformed(evt);
            }
        });
        getContentPane().add(T_book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1057, 186, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rs. 6,531/-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Taj Club Room King Bed City Or Pool View");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 273, 432, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html>Rate Includes Accommodation, Buffet Breakfast At Capital Kitchen,<br> 1 Way Airport Transfer, Lounge Access, Butler Service And WiFi For 4 Devices.<br> Minimum Stay Of 2 Nights. Early Departure Fee Applicable.</html>");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 304, 432, 58));

        T_book2.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        T_book2.setText("Book Now");
        T_book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_book2ActionPerformed(evt);
            }
        });
        getContentPane().add(T_book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1057, 368, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rs. 9,134/-");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 369, -1, 30));

        jLabel10.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Garden Luxury Suite King Bed Pool View");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 427, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<html>Rate Includes Accommodation, Buffet Breakfast At Capital Kitchen,<br> 1 Way Airport Transfer, Lounge Access, Butler Service And WiFi For 4 Devices.<br> Minimum Stay Of 2 Nights. Early Departure Fee Applicable.</html>");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 458, 432, 50));

        T_book3.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        T_book3.setText("Book Now");
        T_book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_book3ActionPerformed(evt);
            }
        });
        getContentPane().add(T_book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1057, 514, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rs. 32,375/-");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Amenities");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 139, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/Amenities.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 188, 366, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("* To see full view of room click on picture");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delhi/Images/Back 1.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic1ActionPerformed
        Taj_pic1 open = new Taj_pic1();
        open.setVisible(true);
    }//GEN-LAST:event_pic1ActionPerformed

    private void pic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic2ActionPerformed
        Taj_pic2 open = new Taj_pic2();
        open.setVisible(true);
    }//GEN-LAST:event_pic2ActionPerformed

    private void pic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic3ActionPerformed
        Taj_pic3 open = new Taj_pic3();
        open.setVisible(true);
    }//GEN-LAST:event_pic3ActionPerformed

    private void T_book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_book1ActionPerformed
        BookingUI open = new BookingUI();
        open.setVisible(true);
        open.setDetails_B(City, "Taj Palace","2 Sardar Patel Marg Diplomatic Enclave, New Delhi.", "Superior Room Twin Bed City Or Pool View", rooms, adults, childs, check_in, check_out, 6531);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
    }//GEN-LAST:event_T_book1ActionPerformed

    private void T_book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_book2ActionPerformed
        BookingUI open = new BookingUI();
        open.setDetails_B(City, "Taj Palace","2 Sardar Patel Marg Diplomatic Enclave, New Delhi.", "Taj Club Room King Bed City Or Pool View", rooms, adults, childs, check_in, check_out, 9134);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_T_book2ActionPerformed

    private void T_book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_book3ActionPerformed
        BookingUI open = new BookingUI();
        open.setDetails_B(City, "Taj Palace","2 Sardar Patel Marg Diplomatic Enclave, New Delhi.", "Garden Luxury Suite King Bed Pool View", rooms, adults, childs, check_in, check_out, 32375);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_T_book3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taj_PalaceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taj_PalaceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taj_PalaceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taj_PalaceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taj_PalaceUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton T_book1;
    private javax.swing.JButton T_book2;
    private javax.swing.JButton T_book3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton pic1;
    private javax.swing.JButton pic2;
    private javax.swing.JButton pic3;
    // End of variables declaration//GEN-END:variables
}
