/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotels;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sanjeev
 */
public class User_info extends javax.swing.JFrame {

    Welcome obj = new Welcome();
    String new_f_name = "", new_l_name = "",new_email = "", new_mobile = "", password_new = "";
    String password_old = "";
    String email_old = "";
    int enable = 0;
    
    public void set(String pass, String email)
    {
        password_old = pass;
        email_old = email;
    }
    
    public User_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        l_name_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        f_name_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mobile_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        password_field = new javax.swing.JTextField();
        save = new javax.swing.JToggleButton();
        Home = new javax.swing.JButton();
        edit = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FIRST NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        email_field.setEditable(false);
        email_field.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 540, -1));

        l_name_field.setEditable(false);
        l_name_field.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        getContentPane().add(l_name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 340, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAST NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EMAIL ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        f_name_field.setEditable(false);
        f_name_field.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(f_name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 299, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MOBILE NO.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        mobile_field.setEditable(false);
        mobile_field.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(mobile_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 410, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PASSWORD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        password_field.setEditable(false);
        password_field.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 410, -1));

        save.setBackground(java.awt.Color.red);
        save.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 90, -1));

        Home.setBackground(new java.awt.Color(51, 51, 255));
        Home.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        edit.setBackground(java.awt.Color.red);
        edit.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 29, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user back.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        f_name_field.setEditable(true);
        l_name_field.setEditable(true);
        email_field.setEditable(true);
        mobile_field.setEditable(true);
        password_field.setEditable(true);
        enable += 1;
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if(enable == 0)
            JOptionPane.showMessageDialog(null, "Nothing to be saved its the old Data");
        else
        {
            new_f_name = f_name_field.getText();
            new_l_name = l_name_field.getText();
            new_email = email_field.getText();
            new_mobile = mobile_field.getText();
            password_new = password_field.getText();
            //email_new = obj.email_ID;
        
            if( ((new_f_name.equals(""))==true) && ((new_l_name.equals(""))==true) && ((new_email.equals(""))==true) && ((new_mobile.equals(""))== true) && ((password_new.equals(""))==true))
                    JOptionPane.showMessageDialog(null, "Please fill the form.");
            
            else if((new_f_name.equals("")) == true)
                    JOptionPane.showMessageDialog(null, "Please enter First Name");            
        
            else if((new_l_name.equals("")) == true)
                    JOptionPane.showMessageDialog(null, "Please enter Last Name");
        
            else if((new_email.equals("")) == true)
                    JOptionPane.showMessageDialog(null,"Please enter Email ID");
        
            else if((new_mobile.equals(""))== true)
                    JOptionPane.showMessageDialog(null,"Please enter Mobile No");
        
            else if((password_new.equals("")) == true)
                    JOptionPane.showMessageDialog(null,"Please enter Password");
        
            else if((new_f_name.length())>25)
                    JOptionPane.showMessageDialog(null, "First Name limit exceeded max limit 25");
        
            else if((new_l_name.length())>25)
                    JOptionPane.showMessageDialog(null, "Last Name limit exceeded max limit 25");
        
            else if((new_email.length())>50)
                    JOptionPane.showMessageDialog(null, "Email ID limit exceeded max limit 50");
                        
            else if(( (new_mobile.length() )<10 ) || ( (new_mobile.length() )>10 ))
                    JOptionPane.showMessageDialog(null, "Mobile no. should be of 10 digits.");
        
            else if((password_new.length())>10)
                    JOptionPane.showMessageDialog(null, "Password limit exceeded max limit 10");
        
            else
            {
                obj.frst_name = new_f_name;
                obj.lst_name = new_l_name;
                obj.email_ID = new_email;
                obj.mobile_no = new_mobile;
                //JOptionPane.showMessageDialog(null,obj.frst_name +"\n"+ obj.lst_name +"\n"+ obj.email_ID +"\n"+ obj.mobile_no +"\n"+password_new +"\nEmail old = "+ email_old +"\nPassword old = "+ password_old);
                try
                {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    
                    Connection connect = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","TRAVELDB","123456");
                    
                    PreparedStatement pt = connect.prepareStatement("update USER_NAME set FIRST_NAME = '"+new_f_name+"', LAST_NAME = '"+new_l_name+"', EMAIL_ID = '"+new_email+"', CONTACT_NO = '"+new_mobile+"', PASSWORD = '"+password_new+"' where EMAIL_ID = '"+email_old+"' and PASSWORD = '"+password_old+"' ");
                                
                    int send_toDB = pt.executeUpdate();
                
                    JOptionPane.showMessageDialog(null,"Information Updated.");
            
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Welcome open = new Welcome();
        open.f_name_label.setText(f_name_field.getText());
        open.frst_name = f_name_field.getText();
        open.lst_name = l_name_field.getText();
        open.email_ID = email_field.getText();
        open.mobile_no = mobile_field.getText();
        open.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JToggleButton edit;
    public static javax.swing.JTextField email_field;
    public static javax.swing.JTextField f_name_field;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JTextField l_name_field;
    public static javax.swing.JTextField mobile_field;
    public static javax.swing.JTextField password_field;
    private javax.swing.JToggleButton save;
    // End of variables declaration//GEN-END:variables
}
