/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotels;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Date;
import java.text.ParseException;

import delhi.DelhiUI;
import goa.GoaUI;
import jaipur.JaipurUI;
import mumbai.Mumbai;

/**
 *
 * @author sanjeev
 */
public class Welcome extends javax.swing.JFrame {

    public String frst_name = "", lst_name = "", email_ID = "", mobile_no = "";  
            
    String destination = "";
    int room = 1, adult = 1, child = 0;
    String check_in = null, check_out = null ;
    Date check_in_dt = null, check_out_dt = null;
    
    
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Destination_cbox = new javax.swing.JComboBox<>();
        Check_IN = new datechooser.beans.DateChooserCombo();
        Check_OUT = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Sign_in = new javax.swing.JButton();
        Sign_up = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Rooms_cbox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Adults_cbox = new javax.swing.JComboBox<>();
        Children_cbox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        f_name_label = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 42));

        Destination_cbox.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        Destination_cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City", "Delhi", "Goa", "Jaipur", "Mumbai" }));
        Destination_cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destination_cboxActionPerformed(evt);
            }
        });
        getContentPane().add(Destination_cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 304, 274, -1));

        Check_IN.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
        Check_IN.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
        try {
            Check_IN.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2017, 6, 11),
                new java.util.GregorianCalendar(2017, 6, 11))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    Check_IN.setFieldFont(new java.awt.Font("Estrangelo Edessa", java.awt.Font.PLAIN, 30));
    Check_IN.addCursorMoveListener(new datechooser.events.CursorMoveListener() {
        public void onCursorMove(datechooser.events.CursorMoveEvent evt) {
            Check_INOnCursorMove(evt);
        }
    });
    Check_IN.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            Check_INOnSelectionChange(evt);
        }
    });
    Check_IN.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            Check_INOnCommit(evt);
        }
    });
    getContentPane().add(Check_IN, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 304, 350, 41));

    Check_OUT.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
    Check_OUT.setFormat(0);
    Check_OUT.setFieldFont(new java.awt.Font("Estrangelo Edessa", java.awt.Font.PLAIN, 30));
    getContentPane().add(Check_OUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 304, 350, 41));

    jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Check Out");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 261, -1, 31));

    jLabel3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Check In");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 261, -1, 31));

    jLabel4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Destination");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 251, -1, 41));

    Sign_in.setBackground(new java.awt.Color(51, 51, 255));
    Sign_in.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
    Sign_in.setForeground(new java.awt.Color(255, 255, 255));
    Sign_in.setText("Sign In");
    Sign_in.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Sign_inActionPerformed(evt);
        }
    });
    getContentPane().add(Sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 50, 160, 50));

    Sign_up.setBackground(new java.awt.Color(51, 51, 255));
    Sign_up.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
    Sign_up.setForeground(new java.awt.Color(255, 255, 255));
    Sign_up.setText("Sign Up");
    Sign_up.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Sign_upActionPerformed(evt);
        }
    });
    getContentPane().add(Sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 140, 50));

    Search.setBackground(new java.awt.Color(255, 0, 0));
    Search.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
    Search.setForeground(new java.awt.Color(255, 255, 255));
    Search.setText("Search");
    Search.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            SearchActionPerformed(evt);
        }
    });
    getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 160, 50));

    Rooms_cbox.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
    Rooms_cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Room", "2 Room", "3 Room", "4 Room", "5 Room" }));
    Rooms_cbox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Rooms_cboxActionPerformed(evt);
        }
    });
    getContentPane().add(Rooms_cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 146, -1));

    jLabel5.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Rooms");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

    jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Adults");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 90, -1));

    Adults_cbox.setFont(new java.awt.Font("Estrangelo Edessa", 0, 30)); // NOI18N
    Adults_cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
    Adults_cbox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Adults_cboxActionPerformed(evt);
        }
    });
    getContentPane().add(Adults_cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 70, -1));

    Children_cbox.setFont(new java.awt.Font("Estrangelo Edessa", 0, 30)); // NOI18N
    Children_cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3","4","5","6","7","8","9","10" }));
    Children_cbox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Children_cboxActionPerformed(evt);
        }
    });
    getContentPane().add(Children_cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 70, -1));

    jLabel7.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Children");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

    f_name_label.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
    f_name_label.setForeground(new java.awt.Color(255, 255, 255));
    getContentPane().add(f_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 490, 40));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
    getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 120));

    jLabel10.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(255, 255, 255));
    jLabel10.setText("TRAVEL INDIA");
    getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 340, 60));

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welcome back.jpg"))); // NOI18N
    getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 670));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_upActionPerformed
        Sign_Up open = new Sign_Up();
        open.setVisible(true);
    }//GEN-LAST:event_Sign_upActionPerformed

    private void Adults_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adults_cboxActionPerformed
        adult = Adults_cbox.getSelectedIndex();
        adult += 1;
    }//GEN-LAST:event_Adults_cboxActionPerformed

    private void Destination_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destination_cboxActionPerformed
        destination = Destination_cbox.getSelectedItem().toString();
    }//GEN-LAST:event_Destination_cboxActionPerformed

    private void Children_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Children_cboxActionPerformed
        child = Children_cbox.getSelectedIndex();        
    }//GEN-LAST:event_Children_cboxActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        
        check_in = Check_IN.getText();
        check_out = Check_OUT.getText();
        
        try{
            //converting string into date.
            SimpleDateFormat sdfIN = new SimpleDateFormat("EEEE, dd MMM, yyyy");//EEEE stands for day(tuesday),dd for date(11), MMM for month(JULY),yyyy for year(2017)
            check_in_dt = sdfIN.parse(check_in);
            check_out_dt = sdfIN.parse(check_out);
            //converting date into string.
            //DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            //check_in = df.format(check_in_dt);
            //check_out = df.format(check_out_dt);

        }
        catch(ParseException ex)
        {
            JOptionPane.showMessageDialog(null,"Select Check In date and Check Out Date again","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        if(destination.equals(""))
            JOptionPane.showMessageDialog(null," Please Select Destination ");
        else if(room>adult)
            JOptionPane.showMessageDialog(null," Please Select More adults ");
        else if((room == 1) && (adult > 2) )
            JOptionPane.showMessageDialog(null, "Please Select more rooms");
        else if(check_in_dt.equals("")==true)
            JOptionPane.showMessageDialog(null," Please Select Check In Date");
        else if(check_out_dt.equals("")==true)
            JOptionPane.showMessageDialog(null," Please Select Check Out Date");
        else if(check_in_dt.after(check_out_dt))
            JOptionPane.showMessageDialog(null," Please check your Check In and Check Out dates.");
        else if(check_in_dt.equals(check_out_dt))
            JOptionPane.showMessageDialog(null," Please check your Check In and Check Out dates as they both cannot be same.");
        else
        {
            //JOptionPane.showMessageDialog(null,"IN= " + check_in + "\nOUT= " + check_out + "\nDestination = " + destination + "\nRooms =" + room + "\nadult = " + adult + "\nchild =" + child);
            switch(destination)
            {
                case "Delhi":   DelhiUI open = new DelhiUI();
                                if(frst_name.equals("")==true)
                                    JOptionPane.showMessageDialog(null,"Please Sign In");
                                else
                                {       
                                    open.setDetails(room, adult, child, check_in_dt, check_out_dt);
                                    open.set_user_info(frst_name, lst_name, email_ID, mobile_no);
                                    open.setVisible(true);
                                }
                                break;
                
                case "Goa":   GoaUI open2 = new GoaUI();
                              if(frst_name.equals("")==true)
                                    JOptionPane.showMessageDialog(null,"Please Sign In");
                                else
                                {
                                    open2.setDetails(room, adult, child, check_in_dt, check_out_dt);
                                    open2.set_user_info(frst_name, lst_name, email_ID, mobile_no);
                                    open2.setVisible(true);
                                }
                              break;
                
                case "Jaipur":   JaipurUI open3 = new JaipurUI();
                                if(frst_name.equals("")==true)
                                    JOptionPane.showMessageDialog(null,"Please Sign In");
                                else
                                {
                                    open3.setDetails(room, adult, child, check_in_dt, check_out_dt);
                                    open3.set_user_info(frst_name, lst_name, email_ID, mobile_no);
                                    open3.setVisible(true);
                                }
                                break;
                
                case "Mumbai":   Mumbai open4 = new Mumbai();
                                if(frst_name.equals("")==true)
                                    JOptionPane.showMessageDialog(null,"Please Sign In");
                                else
                                {
                                    open4.setDetails(room, adult, child, check_in_dt, check_out_dt);
                                    open4.set_user_info(frst_name, lst_name, email_ID, mobile_no);
                                    open4.setVisible(true);
                                }
                                break;
                default:
                            JOptionPane.showMessageDialog(null," Please Select Detination ");
                            break;                               
            }
        }
            
    }//GEN-LAST:event_SearchActionPerformed

    private void Rooms_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rooms_cboxActionPerformed
        room = Rooms_cbox.getSelectedIndex();
        room += 1;
    }//GEN-LAST:event_Rooms_cboxActionPerformed

    private void Sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_inActionPerformed
        Login open_login = new Login();
        open_login.setVisible(true);
    }//GEN-LAST:event_Sign_inActionPerformed

    private void Check_INOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_Check_INOnCommit
        
    }//GEN-LAST:event_Check_INOnCommit

    private void Check_INOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_Check_INOnSelectionChange
        
    }//GEN-LAST:event_Check_INOnSelectionChange

    private void Check_INOnCursorMove(datechooser.events.CursorMoveEvent evt) {//GEN-FIRST:event_Check_INOnCursorMove
        
    }//GEN-LAST:event_Check_INOnCursorMove

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Adults_cbox;
    private datechooser.beans.DateChooserCombo Check_IN;
    private datechooser.beans.DateChooserCombo Check_OUT;
    private javax.swing.JComboBox<String> Children_cbox;
    private javax.swing.JComboBox<String> Destination_cbox;
    private javax.swing.JComboBox<String> Rooms_cbox;
    private javax.swing.JButton Search;
    private javax.swing.JButton Sign_in;
    private javax.swing.JButton Sign_up;
    public javax.swing.JLabel f_name_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
