/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jaipur;

import booking.BookingUI;

/**
 *
 * @author jsc
 */
public class Hyatt_RegencyUI extends javax.swing.JFrame {

    String City = "Jaipur";
    public String check_in = "", check_out = "";
    public int rooms , adults , childs ;
    public void setDetails(int room, int adult,int child,String c_in, String c_out)
    {
        rooms = room;
        adults = adult;
        childs = child;
        check_in = c_in;
        check_out = c_out;
        //JOptionPane.showMessageDialog(null,rooms + " " + adults + " " + childs + " " + check_in + " " + check_out);
    }
    
    String first_name = "", last_name = "",email_ID = "", mobile_no = "";
    
    public void set_user_info(String f_name, String l_name, String email,String mobile)
    {
        first_name = f_name;
        last_name = l_name;
        email_ID = email;
        mobile_no = mobile;
    }
    public Hyatt_RegencyUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        H_pic3 = new javax.swing.JButton();
        H_pic2 = new javax.swing.JButton();
        H_pic1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        H_book1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        H_book2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        H_book3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaipur/Hyatt regency logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, 108));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("HYATT Regency");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 463, 90));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText(" Plot No. 6, Plaza Mall, G T Road, Sec.36, Jaipur");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 310, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Amenities");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 203, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaipur/Amenities.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 254, 280, 70));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("<html>Reception, Free Wi-Fi, Internet, Indoor, Swimming Pool, Valet Parking, Cafe, Restaurent, Bar, Gymnasium/Health, Club, Airport, Shuttle, Body Treatment, Massage, Steam Bath, Sauna, Spa, Business Service, conference Facilities, Baby Sitting/Child Service, Children's Play Area, Car Rental, Board Room, Business Center, Room Service, Travel Desk, Tennis Court, Translation Service, Live Entertainment and more....<html>");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 344, 244, 218));

        H_pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hyattRiver-View-Room.2 - Copy.jpg"))); // NOI18N
        H_pic3.setText("jButton1");
        H_pic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_pic3ActionPerformed(evt);
            }
        });
        getContentPane().add(H_pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 511, 160, 120));

        H_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hyattpic2 - Copy.jpg"))); // NOI18N
        H_pic2.setText("jButton3");
        H_pic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_pic2ActionPerformed(evt);
            }
        });
        getContentPane().add(H_pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 361, 160, 120));

        H_pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hyatt pic1 - Copy.jpg"))); // NOI18N
        H_pic1.setText("jButton2");
        H_pic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_pic1ActionPerformed(evt);
            }
        });
        getContentPane().add(H_pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 211, 160, 120));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Lanai Room It is a Room with Good View");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 191, 520, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("<html>Minimum stay of two nights.Rate includes basic wi-fi up to 4 devices.Early departure fee application<html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 241, 500, 50));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Rs.6,500/-");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 308, 120, 30));

        H_book1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        H_book1.setText("Book Now");
        H_book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_book1ActionPerformed(evt);
            }
        });
        getContentPane().add(H_book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 291, 140, 30));

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Hyatt Club Room King bed City or Pool View");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 351, -1, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<html>Room includes accomodation Buffet Break fast At Capital Kitchen,One way Airport,Butler Service,Wi-Fi Connected fo 4 devices,Minimum  stay of Two Nights.Early Departure Fee Application<html>");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 401, 480, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Rs.8,650/-");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 451, 120, -1));

        H_book2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        H_book2.setText("Book Now");
        H_book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_book2ActionPerformed(evt);
            }
        });
        getContentPane().add(H_book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 451, 140, 30));

        jLabel13.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("<html>Solarium This Type Of Room Is Covered By Glasses Which Allows Sun Rays To Filter In.<html>");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 511, 580, 60));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("<html>For two persons with en suite bath/shower/WC, hair dryer, balcony, double bed, cable TV, radio, safe and free WiFi<html>");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 581, 520, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Rs.11,320/-");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 622, 130, 30));

        H_book3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        H_book3.setText("Book Now");
        H_book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H_book3ActionPerformed(evt);
            }
        });
        getContentPane().add(H_book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 623, 140, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("*To See Full View Of Room Click On Room Image");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, 280, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaipur/leelablur.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void H_pic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_pic3ActionPerformed
        Grand_pic3 open = new Grand_pic3();
        open.setVisible(true);
    }//GEN-LAST:event_H_pic3ActionPerformed

    private void H_pic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_pic1ActionPerformed
        Grand_pic1 open = new Grand_pic1();
        open.setVisible(true);
    }//GEN-LAST:event_H_pic1ActionPerformed

    private void H_book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_book1ActionPerformed
        BookingUI open = new BookingUI();        
        open.setDetails_B(City, "HYATT Regency"," Plot No. 6, Plaza Mall, G T Road, Sec.36, Jaipur", "Lanai Room It is a Room with Good View", rooms, adults, childs, check_in, check_out, 6500);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_H_book1ActionPerformed

    private void H_book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_book3ActionPerformed
        BookingUI open = new BookingUI();        
        open.setDetails_B(City, "HYATT Regency"," Plot No. 6, Plaza Mall, G T Road, Sec.36, Jaipur", "Solarium Room ", rooms, adults, childs, check_in, check_out, 11320);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_H_book3ActionPerformed

    private void H_pic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_pic2ActionPerformed
        Grand_pic2 open = new Grand_pic2();
        open.setVisible(true);
    }//GEN-LAST:event_H_pic2ActionPerformed

    private void H_book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H_book2ActionPerformed
        BookingUI open = new BookingUI();        
        open.setDetails_B(City, "HYATT Regency"," Plot No. 6, Plaza Mall, G T Road, Sec.36, Jaipur", "Hyatt Club Room King bed City or Pool View", rooms, adults, childs, check_in, check_out, 8650);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_H_book2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hyatt_RegencyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hyatt_RegencyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hyatt_RegencyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hyatt_RegencyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hyatt_RegencyUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton H_book1;
    private javax.swing.JButton H_book2;
    private javax.swing.JButton H_book3;
    private javax.swing.JButton H_pic1;
    private javax.swing.JButton H_pic2;
    private javax.swing.JButton H_pic3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
