/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jaipur;

import booking.BookingUI;

/**
 *
 * @author jsc
 */
public class Leela_PalaceUI extends javax.swing.JFrame {

    String City = "Jaipur";
    public String check_in = "", check_out = "";
    public int rooms , adults , childs ;
    public void setDetails(int room, int adult,int child,String c_in, String c_out)
    {
        rooms = room;
        adults = adult;
        childs = child;
        check_in = c_in;
        check_out = c_out;
        //JOptionPane.showMessageDialog(null,rooms + " " + adults + " " + childs + " " + check_in + " " + check_out);
    }
    
    String first_name = "", last_name = "",email_ID = "", mobile_no = "";
    
    public void set_user_info(String f_name, String l_name, String email,String mobile)
    {
        first_name = f_name;
        last_name = l_name;
        email_ID = email;
        mobile_no = mobile;
    }
    public Leela_PalaceUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        L_pic3 = new javax.swing.JButton();
        L_pic2 = new javax.swing.JButton();
        L_pic1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        L_book1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        L_book2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        L_book3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaipur/leela logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Leela Palace");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 90));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Near Purana Qila Opp.SBI Office");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 213, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Amenities");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 204, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaipur/Amenities.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 255, 170, -1));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("<html>Reception, Free Wi-Fi, Internet, Indoor, Swimming Pool, Valet Parking, Cafe, Restaurent, Bar, Gymnasium/Health, Club, Airport, Shuttle, Body Treatment, Massage, Steam Bath, Sauna, Spa, Business Service, conference Facilities, Baby Sitting/Child Service, Children's Play Area, Car Rental, Board Room, Business Center, Room Service, Travel Desk, Tennis Court, Translation Service, Live Entertainment and more....<html>");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 240, 180));

        L_pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leela pic 3 - Copy.jpg"))); // NOI18N
        L_pic3.setText("jButton1");
        L_pic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_pic3ActionPerformed(evt);
            }
        });
        getContentPane().add(L_pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 517, 160, 120));

        L_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/123.jpg"))); // NOI18N
        L_pic2.setText("jButton3");
        L_pic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_pic2ActionPerformed(evt);
            }
        });
        getContentPane().add(L_pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 367, 150, 120));

        L_pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leelapic1 - Copy.jpg"))); // NOI18N
        L_pic1.setText("jButton2");
        L_pic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_pic1ActionPerformed(evt);
            }
        });
        getContentPane().add(L_pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 217, 150, 120));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Lanai Room It is a Room with Good View");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 520, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("<html>Minimum stay of two nights.Rate includes basic wi-fi up to 4 devices.Early departure fee application<html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 500, 50));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Rs.6,500/-");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 120, 30));

        L_book1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        L_book1.setText("Book Now");
        L_book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_book1ActionPerformed(evt);
            }
        });
        getContentPane().add(L_book1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 140, 30));

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Leela Club Room King bed City or Pool View");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 357, 510, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("<html>Room includes accomodation Buffet Break fast At Capital Kitchen,One way Airport,Butler Service,Wi-Fi Connected fo 4 devices,Minimum  stay of Two Nights.Early Departure Fee Application<html>");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 407, 480, 40));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Rs.8,650/-");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 457, 120, -1));

        L_book2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        L_book2.setText("Book Now");
        L_book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_book2ActionPerformed(evt);
            }
        });
        getContentPane().add(L_book2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 450, 140, 30));

        jLabel13.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("<html>Solarium This Type Of Room Is Covered By Glasses Which Allows Sun Rays To Filter In.<html>");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 517, 580, 60));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("<html>For two persons with en suite bath/shower/WC, hair dryer, balcony, double bed, cable TV, radio, safe and free WiFi<html>");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 520, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Rs.11,240/-");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, 130, 30));

        L_book3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        L_book3.setText("Book Now");
        L_book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_book3ActionPerformed(evt);
            }
        });
        getContentPane().add(L_book3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 620, 140, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("* To See Full Room Image Click On Room Image");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, -1, 30));

        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JWblur.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void L_pic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_pic3ActionPerformed
        Leela_pic3 open = new Leela_pic3();
        open.setVisible(true);
    }//GEN-LAST:event_L_pic3ActionPerformed

    private void L_pic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_pic1ActionPerformed
        Leela_pic1 open = new Leela_pic1();
        open.setVisible(true);
    }//GEN-LAST:event_L_pic1ActionPerformed

    private void L_book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_book1ActionPerformed
        BookingUI open = new BookingUI();        
        open.setDetails_B(City, "Leela Palace","Near Purana Qila Opp.SBI Office", "Lanai Room It is a Room with Good View", rooms, adults, childs, check_in, check_out, 6500);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_L_book1ActionPerformed

    private void L_book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_book3ActionPerformed
        BookingUI open = new BookingUI();        
        open.setDetails_B(City, "Leela Palace","Near Purana Qila Opp.SBI Office", "Solarium Room ", rooms, adults, childs, check_in, check_out, 11240);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_L_book3ActionPerformed

    private void L_pic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_pic2ActionPerformed
        Leela_pic2 open = new Leela_pic2();
        open.setVisible(true);
    }//GEN-LAST:event_L_pic2ActionPerformed

    private void L_book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_book2ActionPerformed
        BookingUI open = new BookingUI();        
        open.setDetails_B(City, "Leela Palace","Near Purana Qila Opp.SBI Office", "Leela Club Room King bed City or Pool View", rooms, adults, childs, check_in, check_out, 8650);
        open.set_user_info(first_name, last_name, email_ID, mobile_no);
        open.setVisible(true);
    }//GEN-LAST:event_L_book2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leela_PalaceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leela_PalaceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leela_PalaceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leela_PalaceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leela_PalaceUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton L_book1;
    private javax.swing.JButton L_book2;
    private javax.swing.JButton L_book3;
    private javax.swing.JButton L_pic1;
    private javax.swing.JButton L_pic2;
    private javax.swing.JButton L_pic3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
